module.exports.descriptors = [
"Cheeky Monkey",
"Chimp",
"Cletus",
"Clinton",
"Clone",
"Club",
"Coats",
"Cobweb",
"Coder",
"Cody",
"Coffee",
"Colombo",
"Colonel",
"Columbus",
"Compound",
"Cookie",
]

// module.exports.places = [
//     'Flats',
//     'Village',
//     'Canyon',
//     'Pond',
//     'Group Camp',
//     'Horse Camp',
//     'Ghost Town',
//     'Camp',
//     'Dispersed Camp',
//     'Backcountry',
//     'River',
//     'Creek',
//     'Creekside',
//     'Bay',
//     'Spring',
//     'Bayshore',
//     'Sands',
//     'Mule Camp',
//     'Hunting Camp',
//     'Cliffs',
//     'Hollow'
// ]
//
